### ISSUE TITLE
black screen 

### ISSUE THREAD

**Issue by bahareth1** [Bouhm/StardewValleyMods#2]
every time I open the map on sdv 1.1 the screen goes black

**Comment by bahareth1** [comment]
for NPC Map Locations mod

**Comment by Bouhm** [comment]
Hi, make sure you have the latest version of SMAPI; there was a minor update.
https://github.com/cjsu/SMAPI/releases

**Comment by monkeymc** [comment]
Me too, And Im very sure use SMAPI 0.40.1.1.

Its black screen and crash after press m button.
I try with start new save game(river town) and press m button in home.
